create table "public"."asd" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."asd" enable row level security;

create table "public"."auth_error_log" (
    "id" bigint generated by default as identity not null,
    "error_message" text,
    "auth_header" text,
    "token" text,
    "claims_id" text,
    "claims_subject" text,
    "claims_audience" text,
    "claims_issuer" text,
    "claims_issued_at" bigint,
    "claims_expired_at" bigint,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."auth_error_log" enable row level security;

create table "public"."internal_activity_log" (
    "id" bigint generated by default as identity not null,
    "operation_type" text,
    "user_id" uuid default gen_random_uuid(),
    "container_id" text,
    "docker_image" text,
    "operation_status" smallint,
    "operation_error" text,
    "operation_commands" text,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."internal_activity_log" enable row level security;

create table "public"."test" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text
);


alter table "public"."test" enable row level security;

CREATE UNIQUE INDEX activity_log_pkey ON public.internal_activity_log USING btree (id);

CREATE UNIQUE INDEX asd_pkey ON public.asd USING btree (id);

CREATE UNIQUE INDEX auth_error_log_pkey ON public.auth_error_log USING btree (id);

CREATE UNIQUE INDEX test_pkey ON public.test USING btree (id);

alter table "public"."asd" add constraint "asd_pkey" PRIMARY KEY using index "asd_pkey";

alter table "public"."auth_error_log" add constraint "auth_error_log_pkey" PRIMARY KEY using index "auth_error_log_pkey";

alter table "public"."internal_activity_log" add constraint "activity_log_pkey" PRIMARY KEY using index "activity_log_pkey";

alter table "public"."test" add constraint "test_pkey" PRIMARY KEY using index "test_pkey";

grant delete on table "public"."asd" to "anon";

grant insert on table "public"."asd" to "anon";

grant references on table "public"."asd" to "anon";

grant select on table "public"."asd" to "anon";

grant trigger on table "public"."asd" to "anon";

grant truncate on table "public"."asd" to "anon";

grant update on table "public"."asd" to "anon";

grant delete on table "public"."asd" to "authenticated";

grant insert on table "public"."asd" to "authenticated";

grant references on table "public"."asd" to "authenticated";

grant select on table "public"."asd" to "authenticated";

grant trigger on table "public"."asd" to "authenticated";

grant truncate on table "public"."asd" to "authenticated";

grant update on table "public"."asd" to "authenticated";

grant delete on table "public"."asd" to "service_role";

grant insert on table "public"."asd" to "service_role";

grant references on table "public"."asd" to "service_role";

grant select on table "public"."asd" to "service_role";

grant trigger on table "public"."asd" to "service_role";

grant truncate on table "public"."asd" to "service_role";

grant update on table "public"."asd" to "service_role";

grant delete on table "public"."auth_error_log" to "anon";

grant insert on table "public"."auth_error_log" to "anon";

grant references on table "public"."auth_error_log" to "anon";

grant select on table "public"."auth_error_log" to "anon";

grant trigger on table "public"."auth_error_log" to "anon";

grant truncate on table "public"."auth_error_log" to "anon";

grant update on table "public"."auth_error_log" to "anon";

grant delete on table "public"."auth_error_log" to "authenticated";

grant insert on table "public"."auth_error_log" to "authenticated";

grant references on table "public"."auth_error_log" to "authenticated";

grant select on table "public"."auth_error_log" to "authenticated";

grant trigger on table "public"."auth_error_log" to "authenticated";

grant truncate on table "public"."auth_error_log" to "authenticated";

grant update on table "public"."auth_error_log" to "authenticated";

grant delete on table "public"."auth_error_log" to "service_role";

grant insert on table "public"."auth_error_log" to "service_role";

grant references on table "public"."auth_error_log" to "service_role";

grant select on table "public"."auth_error_log" to "service_role";

grant trigger on table "public"."auth_error_log" to "service_role";

grant truncate on table "public"."auth_error_log" to "service_role";

grant update on table "public"."auth_error_log" to "service_role";

grant delete on table "public"."internal_activity_log" to "anon";

grant insert on table "public"."internal_activity_log" to "anon";

grant references on table "public"."internal_activity_log" to "anon";

grant select on table "public"."internal_activity_log" to "anon";

grant trigger on table "public"."internal_activity_log" to "anon";

grant truncate on table "public"."internal_activity_log" to "anon";

grant update on table "public"."internal_activity_log" to "anon";

grant delete on table "public"."internal_activity_log" to "authenticated";

grant insert on table "public"."internal_activity_log" to "authenticated";

grant references on table "public"."internal_activity_log" to "authenticated";

grant select on table "public"."internal_activity_log" to "authenticated";

grant trigger on table "public"."internal_activity_log" to "authenticated";

grant truncate on table "public"."internal_activity_log" to "authenticated";

grant update on table "public"."internal_activity_log" to "authenticated";

grant delete on table "public"."internal_activity_log" to "service_role";

grant insert on table "public"."internal_activity_log" to "service_role";

grant references on table "public"."internal_activity_log" to "service_role";

grant select on table "public"."internal_activity_log" to "service_role";

grant trigger on table "public"."internal_activity_log" to "service_role";

grant truncate on table "public"."internal_activity_log" to "service_role";

grant update on table "public"."internal_activity_log" to "service_role";

grant delete on table "public"."test" to "anon";

grant insert on table "public"."test" to "anon";

grant references on table "public"."test" to "anon";

grant select on table "public"."test" to "anon";

grant trigger on table "public"."test" to "anon";

grant truncate on table "public"."test" to "anon";

grant update on table "public"."test" to "anon";

grant delete on table "public"."test" to "authenticated";

grant insert on table "public"."test" to "authenticated";

grant references on table "public"."test" to "authenticated";

grant select on table "public"."test" to "authenticated";

grant trigger on table "public"."test" to "authenticated";

grant truncate on table "public"."test" to "authenticated";

grant update on table "public"."test" to "authenticated";

grant delete on table "public"."test" to "service_role";

grant insert on table "public"."test" to "service_role";

grant references on table "public"."test" to "service_role";

grant select on table "public"."test" to "service_role";

grant trigger on table "public"."test" to "service_role";

grant truncate on table "public"."test" to "service_role";

grant update on table "public"."test" to "service_role";


